platform :ios, '13.0'

target 'PagingLayoutSamples' do
  use_frameworks!
  pod 'CollectionViewPagingLayout', :path => './../'
  pod 'Splash', :git => 'https://github.com/amirdew/Splash.git'
  pod 'SwiftLint'
end
